### ISSUE TITLE
1.18.1 Packing tent with a chest crashes the game

### ISSUE THREAD

**Issue by MJRamon** [TerraformersMC/Campanion#160]
campanion-3.0.0

Placed big tent. Placed empty chest inside. Broke with empty tent bag in hand, game crashed.

```
[09:22:08] [Render thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2586.method_31662(net.minecraft.class_1937)" because "entity" is null
	at com.terraformersmc.campanion.client.renderer.item.FakeWorld.lambda$getBlockEntity$1(FakeWorld.java:78) ~[campanion-3.0.0.jar:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
	at com.terraformersmc.campanion.client.renderer.item.FakeWorld.method_8321(FakeWorld.java:73) ~[campanion-3.0.0.jar:?]
	at com.terraformersmc.campanion.client.renderer.item.BuiltTentItemRenderer.renderFakeBlock(BuiltTentItemRenderer.java:50) ~[campanion-3.0.0.jar:?]
	at com.terraformersmc.campanion.client.renderer.item.BuiltTentItemRenderer.lambda$render$0(BuiltTentItemRenderer.java:34) ~[campanion-3.0.0.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at com.terraformersmc.campanion.client.renderer.item.BuiltTentItemRenderer.render(BuiltTentItemRenderer.java:31) ~[campanion-3.0.0.jar:?]
	at net.minecraft.class_918.handler$bcl000$renderItem(class_918.java:536) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_23177(class_918.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_759.method_3233(class_759.java:163) ~[client-intermediary.jar:?]
	at net.minecraft.class_759.method_3228(class_759.java:584) ~[client-intermediary.jar:?]
	at net.minecraft.class_759.method_22976(class_759.java:364) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3172(class_757.java:747) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1057) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:811) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1117) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

```
Stacktrace:
	at com.terraformersmc.campanion.client.renderer.item.FakeWorld.lambda$getBlockEntity$1(FakeWorld.java:78)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at com.terraformersmc.campanion.client.renderer.item.FakeWorld.method_8321(FakeWorld.java:73)
	at com.terraformersmc.campanion.client.renderer.item.BuiltTentItemRenderer.renderFakeBlock(BuiltTentItemRenderer.java:50)
	at com.terraformersmc.campanion.client.renderer.item.BuiltTentItemRenderer.lambda$render$0(BuiltTentItemRenderer.java:34)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at com.terraformersmc.campanion.client.renderer.item.BuiltTentItemRenderer.render(BuiltTentItemRenderer.java:31)
	at net.minecraft.class_918.handler$bcl000$renderItem(class_918.java:536)
	at net.minecraft.class_918.method_23177(class_918.java)
	at net.minecraft.class_759.method_3233(class_759.java:163)
	at net.minecraft.class_759.method_3228(class_759.java:584)
	at net.minecraft.class_759.method_22976(class_759.java:364)
	at net.minecraft.class_757.method_3172(class_757.java:747)
	at net.minecraft.class_757.method_3188(class_757.java:1057)
```

```
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by jhbuchanan45** [comment]
It's fixed in the next version. Since I haven't heard of any other issues, that'll probably release very soon.
