### ISSUE TITLE
Crash on placing sleeping bag 

### ISSUE THREAD

**Issue by C-F-K** [TerraformersMC/Campanion#35]
What it says on the tin. If there are restrictions on how or where to place a sleeping bag, I'm unaware of them. For completeness' sake: I'm also using a few crafting recipe tweaks, but I didn't include them since I doubt they're relevant. Crash dump follows:

(P.S. This mod is fantastic and its content should honestly be in vanilla. How are they gonna give us campfires but no sleeping bags and tents?)

```
[17:52:56] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchFieldError: field_9247
	at com.terraformersmc.campanion.item.SleepingBagItem.method_7836(SleepingBagItem.java:57) ~[Campanion-Mod-Fabric-1.16.jar:?]
	at net.minecraft.class_1799.method_7913(class_1799.java:225) ~[intermediary-minecraft-1.16-client.jar:?]
	at net.minecraft.class_3225.method_14256(class_3225.java:283) ~[intermediary-minecraft-1.16-client.jar:?]
	at net.minecraft.class_3244.method_12065(class_3244.java:1012) ~[intermediary-minecraft-1.16-client.jar:?]
	at net.minecraft.class_2886.method_12550(class_2886.java:31) ~[intermediary-minecraft-1.16-client.jar:?]
	at net.minecraft.class_2886.method_11054(class_2886.java:9) ~[intermediary-minecraft-1.16-client.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-minecraft-1.16-client.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-minecraft-1.16-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-minecraft-1.16-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-minecraft-1.16-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:763) ~[intermediary-minecraft-1.16-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:154) ~[intermediary-minecraft-1.16-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-minecraft-1.16-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:745) ~[intermediary-minecraft-1.16-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:739) ~[intermediary-minecraft-1.16-client.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-minecraft-1.16-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:724) ~[intermediary-minecraft-1.16-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[intermediary-minecraft-1.16-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256) ~[intermediary-minecraft-1.16-client.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[17:52:56] [Server thread/ERROR]: This crash report has been saved to: C:\Users\CFK\Documents\games and shit\minecraft\MultiMC\instances\1.16\.minecraft\crash-reports\crash-2020-06-24_17.52.56-server.txt
[17:52:56] [Server thread/INFO]: Stopping server
[17:52:56] [Server thread/INFO]: Saving players
[17:52:56] [Server thread/INFO]: CKtD lost connection: Disconnected
[17:52:56] [Server thread/INFO]: CKtD left the game
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 6/24/20 5:52 PM
Description: Exception in server tick loop

java.lang.NoSuchFieldError: field_9247
	at com.terraformersmc.campanion.item.SleepingBagItem.method_7836(SleepingBagItem.java:57)
	at net.minecraft.class_1799.method_7913(class_1799.java:225)
	at net.minecraft.class_3225.method_14256(class_3225.java:283)
	at net.minecraft.class_3244.method_12065(class_3244.java:1012)
	at net.minecraft.class_2886.method_12550(class_2886.java:31)
	at net.minecraft.class_2886.method_11054(class_2886.java:9)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:763)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:154)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:745)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:739)
	at net.minecraft.class_1255.method_18857(class_1255.java:127)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:724)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16
	Minecraft Version ID: 1.16
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 414862040 bytes (395 MB) / 1291321344 bytes (1231 MB) up to 1908932608 bytes (1820 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx2048m
	Fabric Mods: 
		campanion: Campanion 1.1.4+build.13
		fabric: Fabric API 0.13.1+build.370-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c7c
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea8667c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea897c
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533987c
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308367c
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f7c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8667c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d7c
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b30537c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f7c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.3+0d474ec47c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96367c
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+e16a97747c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c57c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.10+059ea8667c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce997c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d67c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b7c
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f7c
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.5+e00ecb5f7c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.0+da175ad67c
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a707c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c7c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb87c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.1+059ea8667c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a607c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d7c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.7+12a8474c7c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104907c
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d77c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.5+059ea8667c
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.0.1+f362c86e7c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.5+5a6e8f4c7c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb87c
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.4+5794386e7c
		fabricloader: Fabric Loader 0.8.8+build.202
		minecraft: Minecraft 1.16
	Player Count: 1 / 8; [class_3222['CKtD'/173, l='ServerLevel[Quarantine]', x=855.78, y=72.00, z=-615.19]]
	Data Packs: vanilla, fabric/fabric-tool-attribute-api-v1, fabric/campanion, file/VanillaTweaks_c950931.zip
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\CFK\Documents\games and shit\minecraft\MultiMC\instances\1.16\.minecraft\crash-reports\crash-2020-06-24_17.52.56-server.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.

```

**Comment by Prospector** [comment]
You're running a really old version of Campanion, update to v1.1.10 https://www.curseforge.com/minecraft/mc-mods/campanion/files/2986615

**Comment by C-F-K** [comment]
Huh. Not sure how that happened. Well, thanks :>

**Comment by Prospector** [comment]
I'm surprised it didn't crash on startup!
