### ISSUE TITLE
Campanian crashes carpet when opening/creating a world

### ISSUE THREAD

**Issue by vulntsar** [TerraformersMC/Campanion#64]
When using both carpet and Campanian it crashes when trying to create/open a world I'm leaving a crash log for people who are interested.
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 07/08/20 16:28
Description: Starting integrated server

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_1132.<init>(class_1132.java:54)
	at net.minecraft.class_310.method_29603(class_310.java:1799)
	at net.minecraft.class_310$$Lambda$4901/169222118.apply(Unknown Source)
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:259)
	at net.minecraft.class_310.method_29610(class_310.java:1799)
	at net.minecraft.class_310.method_29606(class_310.java:1698)
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:408)
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:319)
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:256)
	at net.minecraft.class_350.method_25402(class_350.java:331)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:92)
	at net.minecraft.class_312$$Lambda$3418/1822874454.run(Unknown Source)
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_312$$Lambda$3417/1464009366.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at net.minecraft.class_312$$Lambda$2821/1855715730.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127)
	at net.minecraft.class_310.method_1523(class_310.java:1044)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method modifyReachDistance(D)D in mixins.reach-entity-attributes.json:ServerPlayerInteractionManagerMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap reach-entity-attributes-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 40 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_1132.<init>(class_1132.java:54)
	at net.minecraft.class_310.method_29603(class_310.java:1799)
	at net.minecraft.class_310$$Lambda$4901/169222118.apply(Unknown Source)
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:259)

-- Starting integrated server --
Details:
	Level ID: New World (4)
	Level Name: New World
Stacktrace:
	at net.minecraft.class_310.method_29610(class_310.java:1799)
	at net.minecraft.class_310.method_29606(class_310.java:1698)
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:408)
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:319)
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:256)
	at net.minecraft.class_350.method_25402(class_350.java:331)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:92)
	at net.minecraft.class_312$$Lambda$3418/1822874454.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_526
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_312$$Lambda$3417/1464009366.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at net.minecraft.class_312$$Lambda$2821/1855715730.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127)
	at net.minecraft.class_310.method_1523(class_310.java:1044)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

**Comment by Linguardium** [comment]
already reported to the underlying mod here: https://github.com/JamiesWhiteShirt/reach-entity-attributes/issues/1

**Comment by NeusFear** [comment]
This is an issue with carpet
They need to use the lib, or we need to just get entity attributes merged into fapi so things like this don't cause issues. We use the lib to increate compatibility
