### ISSUE TITLE
[1.16.2] Tent Item Rendering cause Crash

### ISSUE THREAD

**Issue by aschjo** [TerraformersMC/Campanion#66]
In a Multi-player Server, when placing the tent in a tent bag in your inventory to a selected hot-bar causes all the players in the server to disconnect with the following crash report:

```---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2020-08-14, 4:49 p.m.
Description: Unexpected error

java.lang.NoSuchMethodError: 'net.minecraft.class_5321 net.minecraft.class_638.method_29287()'
	at com.terraformersmc.campanion.client.renderer.item.FakeWorld.<init>(FakeWorld.java:32)
	at com.terraformersmc.campanion.client.renderer.item.BuiltTentItemRenderer.render(BuiltTentItemRenderer.java:29)
	at net.minecraft.class_761.handler$zem000$render(class_761.java:4639)
	at net.minecraft.class_761.method_22710(class_761.java:1298)
	at net.minecraft.class_757.method_3188(class_757.java:727)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1023)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.terraformersmc.campanion.client.renderer.item.FakeWorld.<init>(FakeWorld.java:32)
	at com.terraformersmc.campanion.client.renderer.item.BuiltTentItemRenderer.render(BuiltTentItemRenderer.java:29)
	at net.minecraft.class_761.handler$zem000$render(class_761.java:4639)
	at net.minecraft.class_761.method_22710(class_761.java:1298)
	at net.minecraft.class_757.method_3188(class_757.java:727)

-- Affected level --
Details:
	All players: 1 total; [class_746['Elteragxo'/37538, l='ClientLevel', x=429.42, y=80.00, z=144.10]]
	Chunk stats: Client Chunk Cache: 729, 441
	Level dimension: minecraft:overworld
	Level spawn location: World: (61,63,92), Chunk: (at 13,3,12 in 3,5; contains blocks 48,0,80 to 63,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 160229 game time, 201995 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2183)
	at net.minecraft.class_310.method_1514(class_310.java:679)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Linux (amd64) version 5.7.14-200.fc32.x86_64
	Java Version: 11.0.7, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1441055680 bytes (1374 MB) / 1979711488 bytes (1888 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 8 total; -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.6
		astromine: Astromine 1.6.0
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		beaconsforall: Beacons For All 1.1.0-1.16.1
		bedspreads: Bedspreads 1.0.0-1.16.1
		blade: Blade 1.0.0
		blue_endless_jankson: jankson 1.2.0
		campanion: Campanion 1.1.13+build.35
		cardinal-components-base: Cardinal Components API (base) 2.5.0-nightly.1.16.2-rc2
		cardinal-components-block: Cardinal Components API (blocks) 2.5.0-nightly.1.16.2-rc2
		cardinal-components-chunk: Cardinal Components API (chunks) 2.5.0-nightly.1.16.2-rc2
		cardinal-components-entity: Cardinal Components API (entities) 2.5.0-nightly.1.16.2-rc2
		cardinal-components-item: Cardinal Components API (items) 2.5.0-nightly.1.16.2-rc2
		cardinal-components-level: Cardinal Components API (world saves) 2.5.0-nightly.1.16.2-rc2
		cardinal-components-util: Cardinal Components API (utilities) 2.5.0-nightly.1.16.2-rc2
		cardinal-components-world: Cardinal Components API (worlds) 2.5.0-nightly.1.16.2-rc2
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.7.0-unstable
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.0.7
		couplings: Couplings 1.3.1
		extraorigins: Extra Origins 14
		fabric: Fabric API 0.18.0+build.397-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c4e
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea894e
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533984e
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308364e
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f4e
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8664e
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d4e
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f4e
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b4e
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd14e
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b4e
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96364e
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c64e
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c54e
		fabric-language-kotlin: Fabric Language Kotlin 1.3.72+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b204e
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+fac8f3664e
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce994e
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d64e
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b4e
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.6.0+e81ec80b4e
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+ba4afa574e
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a704e
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.3+e5d3217f4e
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb84e
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+5d32f5834e
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+e2862de64e
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d4e
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.10+e5d3217f4e
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104904e
		fabric-rendering-v1: Fabric Rendering (v1) 1.2.0+fc24ff244e
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.9+e5d3217f4e
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498414e
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c594e
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb84e
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.1+02fb8fda4e
		fabricloader: Fabric Loader 0.9.1+build.205
		fermion: Fermion 2.1.191
		fermion-modkeys: Fermion Modifier Keys 1.8.180-snapshot
		fiber: fiber 0.23.0-1
		haema: Haema 1.2.1
		illuminations: Illuminations 1.0.5
		lambdynlights: LambDynamicLights 1.2.2+1.16.1
		libblockattributes_core: LibBlockAttributes (Core) 0.7.1-pre.9
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.7.1-pre.9
		libblockattributes_items: LibBlockAttributes (Items) 0.7.1-pre.9
		libstructure: Libstructure 1.0
		magna: Magna 1.4.0-1.16.2
		minecraft: Minecraft 1.16.2
		modmenu: Mod Menu 1.14.6+build.31
		morepaths: More Paths 0.0.3
		netherite_plus: Netherite Plus Mod beta-1.9.1
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.72
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.7
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.7
		origins: Origins 1.16.2-0.3.6
		origins-classes: Origins: Classes 1.16.2-1.0.0
		patchouli: Patchouli 1.16-40-FABRIC
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		satin: Satin 1.4.0
		shapes: Shapes 2.0.0+build.10
		sizeentityattributes: Size Entity Attributes 3
		spruceui: SpruceUI 1.5.8
		team_reborn_energy: Energy 0.1.0
		trinkets: Trinkets 2.6.4
		wrenchable: Wrenchable 1.0.0+1.16.1
	Patchouli open book context: n/a
	Launched Version: fabric-loader-0.9.1+build.205-1.16.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 980/PCIe/SSE2 GL version 4.6.0 NVIDIA 440.100, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (Canada)
	CPU: 8x AMD Ryzen 5 2400G with Radeon Vega Graphics```
From there, the crashing continues if the player with the tent reconnects causing all the players to crash.

**Comment by bripley6** [comment]
I had a crash when doing a similar action but I was playing single player. I tried twice and failed to render a tent both times. I'm running this on a Chromebook via Linux.

**Comment by NeusFear** [comment]
Tested on the latest 1.16.2 build 1.2.0 this doesn't seem to happen. please try updating to the official 1.16.2 version.

**Comment by bripley6** [comment]
Confirmed fixed, thank you!!
