### ISSUE TITLE
Crashing 1.16.1

### ISSUE THREAD

**Issue by nuggetblock** [TerraformersMC/Campanion#72]
everytime i load into a world with campanion it crashes i have tried running it without optifabric as other people suggested but that didnt work. I have tried running every version of campanion and fabric api so please help

Crash Log:

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 26/08/20 10:35 AM
Description: Starting integrated server

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_1132.<init>(class_1132.java:68)
	at net.minecraft.class_310.method_29603(class_310.java:1799)
	at net.minecraft.class_310$$Lambda$5107/1220177576.apply(Unknown Source)
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:259)
	at net.minecraft.class_310.method_29610(class_310.java:1799)
	at net.minecraft.class_310.method_29606(class_310.java:1698)
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:408)
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:319)
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:261)
	at net.minecraft.class_350.method_25402(class_350.java:331)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:92)
	at net.minecraft.class_312$$Lambda$3531/2077281813.run(Unknown Source)
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_312$$Lambda$3390/384985104.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:104)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at net.minecraft.class_312$$Lambda$2841/154311019.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127)
	at net.minecraft.class_310.method_1523(class_310.java:1044)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method modifyReachDistance(D)D in mixins.reach-entity-attributes.json:ServerPlayerInteractionManagerMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap reach-entity-attributes-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 40 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_1132.<init>(class_1132.java:68)
	at net.minecraft.class_310.method_29603(class_310.java:1799)
	at net.minecraft.class_310$$Lambda$5107/1220177576.apply(Unknown Source)
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:259)

-- Starting integrated server --
Details:
	Level ID: survival
	Level Name: survival
Stacktrace:
	at net.minecraft.class_310.method_29610(class_310.java:1799)
	at net.minecraft.class_310.method_29606(class_310.java:1698)
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:408)
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:319)
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:261)
	at net.minecraft.class_350.method_25402(class_350.java:331)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:92)
	at net.minecraft.class_312$$Lambda$3531/2077281813.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_526
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_312$$Lambda$3390/384985104.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:104)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at net.minecraft.class_312$$Lambda$2841/154311019.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127)
	at net.minecraft.class_310.method_1523(class_310.java:1044)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1203749480 bytes (1147 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adorn: Adorn 1.10.1+1.16.1
		betterthanmending: BetterThanMending 1.2.0
		campanion: Campanion 1.1.10+build.24
		carpet: Carpet Mod in Fabric 1.4.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.6.0
		craftablehorsearmour: Craftable Horse Armour & Saddle 1.16-1.3-Fabric
		extraalchemy: Extra Alchemy 1.2.1
		fabric: Fabric API 0.15.1+build.380-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474c02
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-language-kotlin: Fabric Language Kotlin 1.3.72+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.1.0+013e49d202
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.6+a2d21ddd02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.3+0a55f37902
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.4+5794386e02
		fabricloader: Fabric Loader 0.9.2+build.206
		immersive_portals: Immersive Portals 0.24
		jankson: Jankson 3.0.0+j1.2.0
		libcd: LibCapableData 2.4.1+1.16-pre2
		libgui: LibGui 2.0.1+1.16.1
		minecraft: Minecraft 1.16.1
		mm: Manningham Mills 2.0
		modmenu: Mod Menu 1.14.5+build.30
		optifabric: Optifabric 1.1.0-beta1
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.72
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.7
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.7
		org_slf4j_slf4j-api: slf4j-api 1.7.30
		org_slf4j_slf4j-simple: slf4j-simple 1.7.30
		org_zeroturnaround_zt-zip: zt-zip 1.14
		parchment: Parchment 1.0.2+1.15.2
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		waila: Hwyla 1.9.22
	Launched Version: fabric-loader-0.9.2+build.206-1.16.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.23, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: optifine
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	OptiFine Version: OptiFine_1.16.1_HD_U_G2
	OptiFine Build: 20200802-005745
	Render Distance Chunks: 7
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.28 High-Motionblur.zip
	OpenGlVersion: 4.6.0 NVIDIA 442.23
	OpenGlRenderer: GeForce GTX 1060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

Mod List:

Adorn-1.10.1+1.16.1
betterthanmending-1.2.0
campanion-1.1.10+build.24
CHAS-1.16-1.3-Fabric
extraalchemy-fabric-1.16.1-1.2.1+build16
fabric-api-0.15.1+build.380-1.16.1
fabric-carpet-1.16.1-1.4.0+v200623_build2
fabric-language-kotlin-1.3.72+build.1
Hwyla-fabric-1.16-1.9.22-74
immersive-portals-0.24-mc1.16.1-fabric
modmenu-1.14.5+build.30
optifabric-1.1.0-beta1
OptiFine_1.16.1_HD_U_G2

**Comment by ghost** [comment]
Could you disable all mods except for fabric api and campanion and send us the crash log for that?

**Comment by nuggetblock** [comment]
its all good i did some testing and turns out it was carpet mod 👍
